name: Run Spark Job

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language'
        required: true
        type: choice
        options:
          - scala
          - py
      filename:
        description: File name (e.g. - HelloWorld, hello_world)'
        required: true

run-name: ${{ github.event.inputs.filename }}.${{ github.event.inputs.language }}

env:
  LANGUAGE: ${{ github.event.inputs.language }}
  INPUT_FILE_NAME: ${{ github.event.inputs.filename }}
  SPARK_VERSION: 3.5.8

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.9' 

      - name: Setup Scala
        run: |
          wget -q https://downloads.lightbend.com/scala/2.12.18/scala-2.12.18.deb
          sudo dpkg -i scala-2.12.18.deb

      - name: Install Spark
        run: |
          wget -q https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz
          tar -xvf spark-${SPARK_VERSION}-bin-hadoop3.tgz

      - name: Install Python Dependencies
        run: |
          if [ "${LANGUAGE}" == "scala" ]; then
            echo "Skipping as input language is scala.."
          else
            pip3 install numpy scipy pandas pyspark scikit-learn ucimlrepo
          fi

      - name: Run
        run: |
          export SPARK_HOME=$(pwd)/spark-${SPARK_VERSION}-bin-hadoop3
          if [ "${LANGUAGE}" == "scala" ]; then
            cd scala
            scalac -cp "$SPARK_HOME/jars/*" com/example/${INPUT_FILE_NAME}.scala
            jar -cvf ${INPUT_FILE_NAME}.jar com/example/*.class
            $SPARK_HOME/bin/spark-submit --class com.example.${INPUT_FILE_NAME} ${INPUT_FILE_NAME}.jar
          else
            cd python
            $SPARK_HOME/bin/spark-submit --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.8.1 ${INPUT_FILE_NAME}.py
          fi
