name: Run Shell Script

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Shell script name (e.g. - hello-world)'
        required: true
      arguments:
        description: 'Arguments'
        required: false

run-name: ${{ github.event.inputs.filename }}.sh

env:
  INPUT_SCRIPT_NAME: ${{ github.event.inputs.filename }}
  ARGS: ${{ github.event.inputs.arguments }}

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup
        run: sudo apt install tree

      - name: Run
        run: |
          cd sh
          bash ${INPUT_SCRIPT_NAME}.sh ${ARGS}
          tree -I .
